- name:  Deploy new leaf switch
  hosts: leafs
  gather_facts: false

  tasks:
  - name: Enable features
    cisco.nxos.nxos_feature:
        feature: "{{ item }}"
    loop: "{{ features }}"

  - name: Enable overlay EVPN
    cisco.nxos.nxos_evpn_global:
      nv_overlay_evpn: true

  - name: Chagen the system mtu to 9216
    cisco.nxos.nxos_system:
      system_mtu: 9216

  - name: Configure hostname
    cisco.nxos.nxos_hostname:
      config:
        hostname: "{{ hostname }}"

  - name: Configure loopback interfaces
    cisco.nxos.nxos_interfaces:
      config:
        - name: "loopback {{ item.id }}"
          enabled: true
    loop: "{{ loopbacks }}"

  - name: Configure loopback interfaces - ip address
    cisco.nxos.nxos_l3_interfaces:
      config:
        - name: "loopback {{ item.id }}"
          ipv4:
            - address: "{{ item.address }}"
    loop: "{{ loopbacks }}"

  - name: Configure underlay interfaces
    cisco.nxos.nxos_interfaces:
      config:
        - name: "Ethernet{{ item.id }}"
          mtu: 9216
          enabled: true
          mode: layer3
    loop: "{{ underlay_interfaces }}"

  - name: Configure underlay interfaces - ip address
    cisco.nxos.nxos_l3_interfaces:
      config:
        - name: "Ethernet{{ item.id }}"
          ipv4:
            - address: "{{ item.address }}"
    loop: "{{ underlay_interfaces }}"

  - name: Enable OSPF
    cisco.nxos.nxos_ospfv2:
      config:
        processes:
          - process_id: "{{ ospf.id }}"
            router_id: "{{ loopbacks[0].address | ansible.utils.ipaddr('address') }}"

  - name: Enable OSPF on loopback interfaces
    cisco.nxos.nxos_ospf_interfaces:
        config:
        - name: "loopback {{ item.id }}"
          address_family:
            - afi: ipv4
              processes:
                - process_id: "{{ ospf.id }}"
                  area:
                    area_id: "{{ ospf.area }}"
    loop: "{{ loopbacks }}"

  - name: Enable OSPF on underlay interfaces 
    cisco.nxos.nxos_ospf_interfaces:
        config:
        - name: "Ethernet{{ item.id }}"
          address_family:
            - afi: ipv4
              processes:
                - process_id: "{{ ospf.id }}"
                  area:
                    area_id: "{{ ospf.area }}"
    loop: "{{ underlay_interfaces }}"

  - name: Enable BGP
    cisco.nxos.nxos_bgp_global:
      config:
        as_number: "{{ bgp.asn }}"
        router_id: "{{ loopbacks[0].address | ansible.utils.ipaddr('address') }}"

  - name: Configure BGP address families
    cisco.nxos.nxos_bgp_address_family:
      config:
        as_number: "{{ bgp.asn }}"
        address_family:
          - afi: ipv4
            safi: unicast
          - afi: l2vpn
            safi: evpn

  - name: Configure VRF BGP address families
    cisco.nxos.nxos_bgp_address_family:
      config:
        as_number: "{{ bgp.asn }}"
        address_family:      
          - afi: ipv4
            safi: unicast
            vrf: "{{ item.name }}"
    loop: "{{ vrfs }}"

  - name: Configure BGP neighbors
    cisco.nxos.nxos_bgp_global:
      config:
        as_number: "{{ bgp.asn }}"
        neighbors:
          - neighbor_address: "{{ item | ansible.utils.ipaddr('address')}}"
            remote_as: "{{ bgp.asn }}"
            update_source: "loopback {{ loopbacks[0].id }}"
    loop: "{{ groups['spines'] | map('extract', hostvars, ['loopbacks', 0, 'address']) | list }}"

  - name: Configure BGP neighbor address families
    cisco.nxos.nxos_bgp_neighbor_address_family:
      config:
        neighbors:
          - as_number: "{{ bgp.asn }}"
            neighbor_address: "{{ item | ansible.utils.ipaddr('address') }}"
            address_family:
              - afi: ipv4
                safi: unicast
              - afi: l2vpn
                safi: evpn
                send_community:
                  both: true
    loop: "{{ groups['spines'] | map('extract', hostvars, ['loopbacks', 0, 'address']) | list }}"

  - name: Create VTEP with BGP learning
    cisco.nxos.nxos_vxlan_vtep:
      interface: "nve1"
      host_reachability: true
      source_interface: "loopback {{ loopbacks[0].id }}"
      shutdown: false

  - name: Create L2 VNIs
    cisco.nxos.nxos_vxlan_vtep_vni:
      interface: "nve1"
      vni: "{{ item }}"
      suppress_arp: true
      ingress_replication: "bgp"
    loop: "{{ vxlan.l2vnis }}"

  - name: Configure L3 VNIs
    cisco.nxos.nxos_vxlan_vtep_vni:
      interface: "nve1"
      vni: "{{ item }}"
      associate_vrf: true
    loop: "{{ vrfs.vrf_vlan.vni }}"

  - name: Set anycast MAC
    cisco.nxos.nxos_overlay_global:
      anycast_gateway_mac: "{{ anycast_gateway_mac.mac_address }}"

  # Overlay Interfaces Configuration
  - name: Configure overlay interface
    cisco.nxos.nxos_interfaces:
      config:
        - name: "{{ item.interface }}"
          enabled: true
          mode: layer2
    loop: "{{ access_interfaces }}"

  - name: Configure overlay interface - VLAN
    cisco.nxos.nxos_l2_interfaces:
      config:
        - name: "{{ item.interface }}"
          access:
            vlan: "{{ item.vlan_id }}"
    loop: "{{ access_interfaces }}"

  # VLANs
  - name: Configure L2VNI VLAN
    cisco.nxos.nxos_vlans:
      config:
        - vlan_id: "{{ item.1.id }}"
          enabled: true
          mapped_vni: "{{ item.1.vni }}"
    loop: "{{ vrfs | subelements('vlans') }}"

  - name: Configure L3VNI VLAN
    cisco.nxos.nxos_vlans:
      config:
        - vlan_id: "{{ vrfs.l3_vni.vlan_id }}"
          enabled: true
          mapped_vni: "{{ vrfs.l3_vni.vni }}"
  
  - name: Configure SVI
    cisco.nxos.nxos_l3_interfaces:
      config:
        - name: "vlan{{ item.1.id }}"
          ipv4:
            - address: "{{ item.1.svi_address }}"
          vrf: "{{ vrfs[vrfs.index(item.0)].name }}"
    loop: "{{ vrfs | subelements('vlans') }}"
    
  - name: Configure SVI (Anycast Gateway)
    cisco.nxos.nxos_interfaces:
      config:
        - name: "vlan{{ item.1.id }}"
          enabled: true
          fabric_forwarding_anycast_gateway : true
    loop: "{{ vrfs | subelements('vlans') }}"

  - name: Configure L3VNI SVI
    cisco.nxos.nxos_l3_interfaces:
      config:
        - name: "vlan{{ l3_vni.vlan_id }}"
          ip_forward : true
    loop: "{{ vrfs }}"

  - name: Configure tenant's VRF
    cisco.nxos.nxos_vrf:
      config:
        - name: "{{ item.name }}"
          rd: "auto"
          vni: "{{ item.l3_vni.vni }}"
    loop: "{{ vrfs }}"

  - name: Configure VRFs address-family
    cisco.nxos.nxos_vrf_af:
      vrf: "{{ item.name }}"
      afi: "ipv4"
      route_target_both_auto_evpn: true
      route_targets:
        - rt: "auto"
          direction: "both"
    loop: "{{ vrfs }}"

  - name: Configure EVPN
    cisco.nxos.nxos_evpn_vni:
      vni: "{{ item.1.vni }}"
      route_distinguisher: "auto"
      route_target_both: "auto"
    loop: "{{ vrfs | subelements('vlans') }}"