- name: Apply Base Configuration to all devices
  hosts: 
    - device_roles_leaf-switch
    - device_roles_spine-switch
  gather_facts: false
  roles:
    - base_config

- name: Configure Underlay Network on Spines
  hosts: device_roles_spine-switch
  gather_facts: false
  roles:
    - underlay_spine_config

- name: Configure Underlay Network on Leafs
  hosts: device_roles_leaf-switch 
  gather_facts: false
  roles:
    - underlay_leaf_config
    
- name: Configure Overlay Network on Leafs
  hosts: device_roles_leaf-switch
  gather_facts: false
  roles:
    - overlay_leaf_config