- name:  Configure L2VPNs & Server Ports on Leaf switchs (Runs on interface changes)
  hosts: "{{ device_name }}"
  gather_facts: false
  
  tasks:
  - name: Parse NetBox data into variable
    set_fact:
      snapshots: "{{ extracted_snapshots | from_yaml }}"
      untagged_vlan: "{{ extracted_untagged_vlan | from_yaml }}"    

  - name: Debug the variable
    debug:
      msg: 
        - "snapshots: {{ snapshots }}"
        - "untagged_vlan: {{ untagged_vlan }}"

  - name: Retrieve all VLAN objects on Netbox
    set_fact:
      vlans: "{{ query('netbox.netbox.nb_lookup', 'vlans',
                    api_endpoint=netbox_url,
                    token=netbox_token) }}"

  - name: Debug the variable vlans
    debug:
      var: vlans

  - name: Fetch Device Current Mapping
    set_fact:
      current_map: "{{ (query('netbox.netbox.nb_lookup', 'devices',
                        api_endpoint=netbox_url,
                        token=netbox_token,
                        api_filter='name='+inventory_hostname
                        ).value.custom_fields.vlan_vni_mapping) | default({}) }}"

  - name: Debug the current_map
    debug:
      var: current_map

  - name: Retrieve used L2VPNs (VLAN objects on Netbox) from interface
    set_fact:
      vlan_ids: "{{ untagged_vlan.id }}"
    when: untagged_vlan is defined

  - name: Debug the current_map
    debug:
      var: vlan_ids
    
  # - name: Configure L2VNI VLANs
  #   cisco.nxos.nxos_vlans:
  #     config:
  #       - vlan_id: "{{ item.1.id }}"
  #         enabled: true
  #         mapped_vni: "{{ item.1.vni }}"
  #   loop: "{{ query('netbox.netbox.nb_lookup', 'vlans',
  #             api_endpoint=netbox_url,
  #             token=netbox_token,
  #             api_filter='device='+inventory_hostname+' name__ic=loopback')
  #             | map(attribute='value') }}"   

  # - name: Configure VRF BGP address families
  #   cisco.nxos.nxos_bgp_address_family:
  #     config:
  #       as_number: "{{ bgp.asn }}"
  #       address_family:      
  #         - afi: ipv4
  #           safi: unicast
  #           vrf: "{{ item.name }}"
  #   loop: "{{ vrfs }}"

  # # HAVEN'T UPDATE L3VNI
  # - name: Configure tenant's VRF
  #   cisco.nxos.nxos_vrf:
  #     name: "{{ item.name }}"
  #     rd: "auto"
  #     vni: "{{ item.l3_vni.vni }}"
  #   loop: "{{ query('netbox.netbox.nb_lookup', 'tenants',
  #             api_endpoint=netbox_url,
  #             token=netbox_token }}"