- name:  Configure L2VPNs & Server Ports on Leaf switchs (Runs on interface changes)
  hosts: "{{ device_name }}"
  gather_facts: false
  
  tasks:
  - name: Parse NetBox data into variable
    set_fact:
      snapshots: "{{ extracted_snapshots | from_yaml }}"
      untagged_vlan: "{{ extracted_untagged_vlan | from_yaml }}"    

  - name: Debug the variables
    debug:
      msg: 
        - "snapshots: {{ snapshots }}"
        - "untagged_vlan: {{ untagged_vlan }}"
        - "device_name: {{ device_name }}"
        - "description: {{ description }}"
        - "enabled: {{ enabled }}"
        - "interface_name: {{ interface_name }}"
        - "switchport_mode: {{ switchport_mode }}"

  - name: Retrieve all L2VPNs (VLAN objects on Netbox)
    set_fact:
      all_l2vpns: "{{ query('netbox.netbox.nb_lookup', 'vlans',
                    api_endpoint=netbox_url,
                    token=netbox_token) }}"

  - name: Debug the mapping query
    debug:
      msg:
        - "{{ ((lookup('netbox.netbox.nb_lookup', 'devices',
                      api_endpoint=netbox_url,
                      token=netbox_token,
                      api_filter='name='+device_name
                      ).value.custom_fields.vlan_vni_mapping) | default({}, true)
                      ) | dict2items }}"

  - name: Retrieve existing VNI-VLAN ID mapping from Device object
    set_fact:
      mapping: "{{ ((lookup('netbox.netbox.nb_lookup', 'devices',
                    api_endpoint=netbox_url,
                    token=netbox_token,
                    api_filter='name='+device_name
                    ).value.custom_fields.vlan_vni_mapping) | default({}, true)
                    ) | dict2items }}"

  - name: Debug the variables
    debug:
      msg:
        - "all_l2vpns: {{ all_l2vpns }}"
        - "mapping: {{ mapping }}"

  - name: Retrieve used L2VPNs (VLAN objects on Netbox) from interface
    set_fact:
      vlan_ids: []

  - name: Retrieve used L2VPNs (VLAN objects on Netbox) from interface
    set_fact:
      vlan_ids: "{{ [untagged_vlan.id] }}"
    when:
      - untagged_vlan is defined
      - untagged_vlan != 'None'

  - name: Set prechange VLAN ids
    set_fact:
      prechange_vlan_ids: []
    
  - set_fact:
      prechange_vlan_ids: "{{ snapshots.prechange.untagged_vlan }}"
    when: snapshots.prechange.untagged_vlan is defined and (snapshots.prechange.untagged_vlan != 'None')

# The vlan_id here is ID of the VLAN not VLAN number!
  - name: Remove unused L2VPNs
    block:
    - name: Create list of VLAN IDs to remove
      set_fact:
        to_remove: []
      
    - set_fact:
        to_remove: "{{ to_remove + [item] }}"
      loop: "{{ prechange_vlan_ids | difference(vlan_ids) }}"
      when: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
                  api_endpoint=netbox_url,
                  token=netbox_token,
                  api_filter='device='+device_name+' vlan_id='+(item | string)) | length == 0}}"
    
    - name: Debug to_remove
      debug:
        var: to_remove

    - name: Filter VLANs to be removed based on IDs
      set_fact:
        remove_l2vpns: "{{ all_l2vpns | selectattr('value.id', 'in', (to_remove | map('int') | list)) | map(attribute='value') }}"     
    
    - name: Debug remove_l2vpns
      debug:
        var: remove_l2vpns

    - name: Convert mapping to o_map
      set_fact:
        o_map: "{{ mapping | items2dict }}"

    - debug:
        var: o_map

    - name: Identify potentially unused Tenants
      set_fact:
        candidate_tenants: "{{ remove_l2vpns | map(attribute='tenant') | unique }}"

    - debug:
        var: candidate_tenants

    # TESTING REMOVING L3VNI VLANs AND VRFS
    # 1. Fetch ALL interfaces on this specific device to audit current usage
    - name: Fetch all interfaces on the device
      set_fact:
        all_device_interfaces: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
                                  api_endpoint=netbox_url,
                                  token=netbox_token,
                                  api_filter='device=' ~ device_name) 
                                  | map(attribute='value') }}"

    # 2. Extract the IDs of ALL VLANs currently assigned to these interfaces
    - name: Build list of VLAN IDs currently in use on this device
      set_fact:
        # Filter interfaces that have an untagged_vlan assigned
        current_used_vlan_ids: "{{ all_device_interfaces 
                                   | selectattr('untagged_vlan', 'defined') 
                                   | selectattr('untagged_vlan', '!=', None)
                                   | map(attribute='untagged_vlan.id') 
                                   | unique 
                                   | list }}"

    - debug:
        var: current_used_vlan_ids

    # 3. Fetch the full VLAN objects for these 'Used IDs'
    #    (We do this to get the 'tenant' field, which was missing in the interface API)
    - name: Fetch details of currently used VLANs to identify their Tenants
      set_fact:
        # NetBox API supports comma-separated list for id__in
        current_used_vlans_objects: "{{ query('netbox.netbox.nb_lookup', 'vlans',
                                        api_endpoint=netbox_url,
                                        token=netbox_token,
                                        api_filter=(current_used_vlan_ids | map('string') | map('regex_replace', '^', 'id=') | join(' ') ) )
                                        | map(attribute='value') }}"
      when: current_used_vlan_ids | length > 0

    - name: Handle empty case
      set_fact:
        current_used_vlans_objects: []
      when: current_used_vlan_ids | length == 0

    # 4. Build a flat list of Tenant IDs that are currently active on the switch
    - name: List active Tenant IDs
      set_fact:
        active_tenant_ids: "{{ current_used_vlans_objects | map(attribute='tenant.id') | unique }}"

    - debug:
        var: active_tenant_ids
    # 5. Determine which Tenants to remove
    #    (Candidate is removed ONLY if its ID is NOT in the active_tenant_ids list)
    - name: Calculate Tenants to Remove
      set_fact:
        tenants_to_remove: "{{ candidate_tenants | rejectattr('id', 'in', active_tenant_ids) | list }}"

    # 6. Proceed with Removal
    - name: Process Removal of Unused Tenants
      block:
        # ---------------------------------------------------------------------
        # FIX: Re-fetch FULL Tenant objects to get custom_fields
        # ---------------------------------------------------------------------
        - name: Fetch full Tenant objects (to access custom_fields)
          set_fact:
            tenants_to_remove_full: "{{ query('netbox.netbox.nb_lookup', 'tenants',
                                        api_endpoint=netbox_url,
                                        token=netbox_token,
                                        api_filter=(tenants_to_remove | map(attribute='id') | map('string') | map('regex_replace', '^', 'id=') | join(' '))) }}"

        - debug:
            var: tenants_to_remove_full
        # ---------------------------------------------------------------------
        # A. Get L3VNI Info using the FULL objects
        # ---------------------------------------------------------------------
        - name: Retrieve L3VNI VLAN Objects for removal
          set_fact:
            remove_l3vpns: "{{ query('netbox.netbox.nb_lookup', 'vlans',
                                api_endpoint=netbox_url,
                                token=netbox_token,
                                api_filter='id=' ~ item.custom_fields.tenant_l3vni.id) }}"
          loop: "{{ tenants_to_remove_full }}"
          register: l3vni_results

        - debug:
            var: l3vni_results

        - set_fact:
            remove_l3vpns_flat: "{{ l3vni_results.results | map(attribute='ansible_facts.remove_l3vpns') | flatten }}"

        - debug:
            var: remove_l3vpns_flat
        # ---------------------------------------------------------------------
        # B. Remove VRF
        # ---------------------------------------------------------------------
        - name: Remove Unused VRFs
          cisco.nxos.nxos_vrf:
            name: "{{ item.slug }}"
            state: absent
          loop: "{{ tenants_to_remove_full }}"

        # ---------------------------------------------------------------------
        # C. Remove L3VNI SVI
        # ---------------------------------------------------------------------
        - name: Remove Unused L3VNI SVIs
          cisco.nxos.nxos_interfaces:
            config:
              - name: "vlan {{ o_map[item.custom_fields.vni | string] }}"
            state: purged
          loop: "{{ remove_l3vpns_flat }}"
          when: o_map[item.custom_fields.vni | string] is defined

        # ---------------------------------------------------------------------
        # D. Remove L3VNI from VTEP
        # ---------------------------------------------------------------------
        - name: Remove Unused L3VNI from VTEP
          cisco.nxos.nxos_vxlan_vtep_vni:
            interface: nve1
            vni: "{{ item.custom_fields.vni }}"
            state: absent
          loop: "{{ remove_l3vpns_flat }}"

        # ---------------------------------------------------------------------
        # E. Remove L3VNI VLAN
        # ---------------------------------------------------------------------
        - name: Remove Unused L3VNI VLANs
          cisco.nxos.nxos_vlans:
            config:
              - vlan_id: "{{ o_map[item.custom_fields.vni | string] }}"
            state: deleted
          loop: "{{ remove_l3vpns_flat }}"
          when: o_map[item.custom_fields.vni | string] is defined

        # ---------------------------------------------------------------------
        # F. Update Mapping
        # ---------------------------------------------------------------------
        - name: Update mapping to remove L3VNIs
          set_fact:
            mapping: "{{ mapping | rejectattr('key', 'in', (remove_l3vpns_flat | map(attribute='custom_fields.vni') | map('string') ) ) }}"
      when: tenants_to_remove | length > 0
    # END OF TESTING

    - name: Remove unused L2VNIs SVIs
      cisco.nxos.nxos_interfaces:
        config:
          - name: "vlan {{ o_map[item.custom_fields.vni | string] }}"
        state: purged
      loop: "{{ remove_l2vpns }}"
    
    - name: Remove unused L2VNIs from VTEP
      cisco.nxos.nxos_vxlan_vtep_vni:
        interface: nve1
        vni: "{{ item.custom_fields.vni }}"
        state: absent
      loop: "{{ remove_l2vpns }}"
    
    - name: Remove unused L2VNIs from EVPN
      cisco.nxos.nxos_evpn_vni:
        vni: "{{ item.custom_fields.vni }}"
        state: absent
      loop: "{{ remove_l2vpns }}"

    - name: Remove unused L2VNI VLANs
      cisco.nxos.nxos_vlans:
        config:
          - vlan_id: "{{ o_map[item.custom_fields.vni | string] }}"
        state: deleted
      loop: "{{ remove_l2vpns }}"

    - name: Update mapping
      set_fact:
        mapping: "{{ mapping | rejectattr('key', 'in', (remove_l2vpns | map(attribute='custom_fields.vni') | map('string') ) )}}"

    when: (prechange_vlan_ids | difference(vlan_ids)) | length > 0
  
  - name: Filter used L2VPNs based on used IDs
    set_fact:
      l2vpns: "{{ all_l2vpns | selectattr('value.id', 'in', vlan_ids) | map(attribute='value') }}"
  
  - name: Debug the l2vpns
    debug:
      var: l2vpns

  - name: Create list of used tenants
    set_fact:
      used_tenants: "{{ l2vpns | map(attribute='tenant.slug') | unique }}"

  - name: Retrieve Tenant objects
    set_fact:
      tenants: []

  - set_fact:
      tenants: "{{ tenants + query('netbox.netbox.nb_lookup', 'tenants',
                    api_endpoint=netbox_url,
                    token=netbox_token,
                    api_filter='slug='+item
                    ) | map(attribute='value') | list }}"
    loop: "{{ used_tenants }}"

  - name: Debug the tenants
    debug:
      var: tenants

  - name: Retrieve L3VNI VLAN objects for these Tenants
    set_fact:
      l3vpns: []
    
  - name: Populate L3VNI VLANs list
    set_fact:
      l3vpns: "{{ l3vpns + query('netbox.netbox.nb_lookup', 'vlans',
                    api_endpoint=netbox_url,
                    token=netbox_token,
                    api_filter='id=' ~ item.custom_fields.tenant_l3vni.id) }}"
    loop: "{{ tenants }}"

  - name: Debug the l3vpns
    debug:
      var: l3vpns

  - name: Update VNI-VLAN ID mapping if needed
    set_fact:
      vnis: "{{ (l2vpns | map(attribute='custom_fields.vni')) + (l3vpns | map(attribute='custom_fields.vni')) }}"
      mapped_vnis: "{{ mapping | map(attribute='key') }}"

  - set_fact:
      max_id: 9
    when: mapping | length == 0

  - set_fact:  
      max_id: "{{ (mapping | sort(attribute='value', reverse=true))[0]['value'] }}"    
    when: mapping | length > 0

  - set_fact:
      mapping: "{{ mapping + [{'key': item, 'value': ((max_id | int) + 1)}] }}"
      max_id: "{{ (max_id | int) + 1}}"
    loop: "{{ vnis | map('string') }}"
    when: not (item in mapped_vnis)

  - set_fact:
      map: "{{ mapping | items2dict }}"

  - name: Update mapping field in Netbox
    netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ device_name }}"
          custom_fields:
            vlan_vni_mapping: "{{ map }}"

  - name: Create VRFs
    cisco.nxos.nxos_vrf:
      name: "{{ item.tenant.slug }}"
      vni: "{{ item.custom_fields.vni }}"
      rd: auto
    loop: "{{ l3vpns }}"

  - name: Create L3VNI VLANs
    cisco.nxos.nxos_vlans:
      config:
        - vlan_id: "{{ map[item.custom_fields.vni | string] }}"
          name: "{{ item.name | replace(' ', '_') }}"
          enabled: true
          mapped_vni: "{{ item.custom_fields.vni }}"
    loop: "{{ l3vpns }}"

  - name: Configure VRFs address-family
    cisco.nxos.nxos_vrf_af:
      vrf: "{{ item.slug }}"
      afi: ipv4
      route_target_both_auto_evpn: true
      route_targets:
        - rt: auto
          direction: both
    loop: "{{ tenants }}"
  
  - name: Configure VRF BGP address families with redistribution
    cisco.nxos.nxos_bgp_address_family:
      config:
        as_number: "{{ bgp.asn }}"
        address_family:      
          - afi: ipv4
            safi: unicast
            vrf: "{{ item.slug }}"
            redistribute:
                - protocol: direct
                  route_map: PERMIT_ALL
    loop: "{{ tenants }}"

  - name: Create L3VNIs SVIs
    cisco.nxos.nxos_interfaces:
      config:
        - name: "Vlan {{ map[item.custom_fields.vni | string] }}"
          enabled: true
    loop: "{{ l3vpns }}"

  - name: Add L3VNIs to VTEP
    cisco.nxos.nxos_vxlan_vtep_vni:
      interface: nve1
      vni: "{{ item.custom_fields.vni }}"
      assoc_vrf: true
    loop: "{{ l3vpns }}"

  - name: Add L3VNIs SVIs to respective VRFs
    cisco.nxos.nxos_vrf_interface:
      vrf: "{{ item.tenant.slug }}"
      interface: "vlan {{ map[item.custom_fields.vni | string] }}"
    loop: "{{ l3vpns }}"
    
  # Need to enable ip forwarding after adding to VRF to prevent loss of config
  - name: Enable IP Forwarding on L3VNI SVIs
    cisco.nxos.nxos_interfaces:
      config:
        - name: "Vlan {{ map[item.custom_fields.vni | string] }}"
          ip_forward: true
    loop: "{{ l3vpns }}"

  - name: Create L2VNI VLANs
    cisco.nxos.nxos_vlans:
      config:
        - vlan_id: "{{ map[item.custom_fields.vni | string] }}"
          name: "{{ item.name | replace(' ', '_') }}"
          enabled: true
          mapped_vni: "{{ item.custom_fields.vni }}"
    loop: "{{ l2vpns }}"

  - name: Create L2VNIs SVIs
    cisco.nxos.nxos_interfaces:
      config:
        - name:  "vlan {{ map[item.custom_fields.vni | string] }}"
          enabled: true
    loop: "{{ l2vpns }}"

  - name: Add L2VNIs to VTEP
    cisco.nxos.nxos_vxlan_vtep_vni:
      interface: nve1
      vni: "{{ item.custom_fields.vni }}"
      suppress_arp: true
      ingress_replication: bgp
    loop: "{{ l2vpns }}"

  - name: Add L2VNIs to EVPN
    cisco.nxos.nxos_evpn_vni:
      vni: "{{ item.custom_fields.vni }}"
      route_distinguisher: auto
      route_target_both: auto
    loop: "{{ l2vpns }}"
  
  - name: Add L2VNIs SVIs to respective VRFs
    cisco.nxos.nxos_vrf_interface:
      vrf: "{{ item.tenant.slug }}"
      interface: "vlan {{ map[item.custom_fields.vni | string] }}"
    loop: "{{ l2vpns }}"

  - name: Configure L2VNI - ip address
    cisco.nxos.nxos_l3_interfaces:
      config:
        - name: "vlan {{ map[item.custom_fields.vni | string] }}"
          ipv4:
          - address: "{{ (ip_prefix | ansible.utils.ipaddr('first_usable')) ~ '/' ~
                  (ip_prefix | ansible.utils.ipaddr('prefix')) }}"
    vars:
      ip_prefix: "{{ query('netbox.netbox.nb_lookup', 'prefixes',
                      api_endpoint=netbox_url,
                      token=netbox_token,
                      api_filter='vlan_id=' ~ item.id)
                      | map(attribute='value')
                      | map(attribute='prefix') 
                      | first }}"
    loop: "{{ l2vpns }}"
    
  - name: Enable anycast gateway on L2VNIs SVIs
    cisco.nxos.nxos_interfaces:
      config:
        - name:  "vlan {{ map[item.custom_fields.vni | string] }}"
          fabric_forwarding_anycast_gateway: true
    loop: "{{ l2vpns }}"

  - name: Configure interface
    cisco.nxos.nxos_interfaces:
        config:
          - name: "{{ interface_name }}"
            description: "{{ description }}"
            enabled: "{{ enabled }}"
  
  - name: Configure interface - mode
    cisco.nxos.nxos_interfaces:
      config:
        - name: "{{ interface_name }}"
          mode: "{{ 'layer2' if (switchport_mode == 'access') else 'layer3' }}"
  
  - name: Configure Access Port
    cisco.nxos.nxos_l2_interfaces:
      config:
        - name: "{{ interface_name }}"
          mode: access
          access:
            vlan: "{{ map[l2vpns[0].custom_fields.vni | string] }}"
      state: replaced
    when: switchport_mode == 'access' and untagged_vlan.vid is defined

  # - name: Configure L2VNI VLANs
  #   cisco.nxos.nxos_vlans:
  #     config:
  #       - vlan_id: "{{ item.1.id }}"
  #         enabled: true
  #         mapped_vni: "{{ item.1.vni }}"
  #   loop: "{{ query('netbox.netbox.nb_lookup', 'vlans',
  #             api_endpoint=netbox_url,
  #             token=netbox_token,
  #             api_filter='device='+inventory_hostname+' name__ic=loopback')
  #             | map(attribute='value') }}"   

  # - name: Configure VRF BGP address families
  #   cisco.nxos.nxos_bgp_address_family:
  #     config:
  #       as_number: "{{ bgp.asn }}"
  #       address_family:      
  #         - afi: ipv4
  #           safi: unicast
  #           vrf: "{{ item.name }}"
  #   loop: "{{ vrfs }}"

  # # HAVEN'T UPDATE L3VNI
  # - name: Configure tenant's VRF
  #   cisco.nxos.nxos_vrf:
  #     name: "{{ item.name }}"
  #     rd: "auto"
  #     vni: "{{ item.l3_vni.vni }}"
  #   loop: "{{ query('netbox.netbox.nb_lookup', 'tenants',
  #             api_endpoint=netbox_url,
  #             token=netbox_token }}"