all:
  children:
    leafs:
      hosts:
        leaf1:
          ansible_host: leaf1
        leaf2:
          ansible_host: leaf2
      vars:
          role: leaf

    spines:
      hosts:
        spine1:
          ansible_host: spine1
        spine2:
          ansible_host: spine2
      vars:
        role: spine
