all:
  children:
    leafs:
      hosts:
        leaf1:
          ansible_host: localhost
          ansible_port: 3224
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o HostKeyAlgorithms=+ssh-rsa'
        leaf2:
          ansible_host: localhost
          ansible_port: 3225
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o HostKeyAlgorithms=+ssh-rsa'
      vars:
          role: leaf

    spines:
      hosts:
        spine1:
          ansible_host: localhost
          ansible_port: 3222
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o HostKeyAlgorithms=+ssh-rsa'
        spine2:
          ansible_host: localhost
          ansible_port: 3223
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o HostKeyAlgorithms=+ssh-rsa'
      vars:
        role: spine
