plugin: netbox.netbox.nb_inventory
api_endpoint: http://20.244.9.88:8000/api/
token: 14d9e67df5aae036a55235d4e8c2f0312f21028a

config_context: False
validate_certs: False # Set to True for production with valid SSL

group_by:
  - device_roles
  - site
  - device_type

compose:
  # Find the service named 'ansible-ssh' and get the first IP address associated with it.
  ansible_host: "services | selectattr('name', 'equalto', 'ansible-ssh') | first | ipaddresses | first | address | split('/') | first"
  # Find the service named 'ansible-ssh' and get its first port number.
  ansible_port: "services | selectattr('name', 'equalto', 'ansible-ssh') | first | ports | first"
  ansible_network_os: platform.slug
