plugin: netbox.netbox.nb_inventory

config_context: False
validate_certs: False # Set to True for production with valid SSL

group_by:
  - device_roles
  - sites
  - platforms

compose:
  # Find the service named 'ansible-ssh' and get the first IP address associated with it.
  ansible_host: custom_fields.ansible_host | default(inventory_hostname, true)
  # Find the service named 'ansible-ssh' and get its first port number.
  ansible_port: custom_fields.ansible_port | default(22, true)
  ansible_network_os: platform.slug
