plugin: netbox.netbox.nb_inventory
api_endpoint: http://20.244.9.88:8000
token: 14d9e67df5aae036a55235d4e8c2f0312f21028a

config_context: False
validate_certs: False # Set to True for production with valid SSL

group_by:
  - device_roles
  - sites
  - platforms

compose:
  # Find the service named 'ansible-ssh' and get the first IP address associated with it.
  ansible_host: custom_fields.ansible_host | default(inventory_hostname, true)
  # Find the service named 'ansible-ssh' and get its first port number.
  ansible_port: custom_fields.ansible_port | default(22, true)
  ansible_network_os: platform.slug
